<?php

class Db extends RubbishThorClone {
  use manifest_io;
  use whippet_helpers;

  public function commands() {
    $this->command('seed [ENV]', 'Seeds the database for the appropriate environment');
  }

  /*
   * Commands
   */

  public function seed($environment) {
    if (!is_string($environment)) {
      echo "Usage: whippet db seed testing\n";
      exit(1);
    }

    $this->whippet_init();

    $yaml = \Symfony\Component\Yaml\Yaml::parse('whippet.yml');
    $parameters = $yaml['whippet'][$environment];

    $this->writeWhippetWpConfig($parameters);

    // Drop tables
    $db = new PDO('mysql:host='.$parameters['db']['host'].';dbname='.$parameters['db']['name'], $parameters['db']['user'], $parameters['db']['pass']);
    foreach ($db->query('SHOW TABLES') as $row) {
      $table = $row[0];
      $db->exec('DROP TABLE `'.$table.'`');
      echo "dropped $table\n";
    }

    // Load WP
    define('WP_INSTALLING', true);

    include($parameters['path'].'/wp-load.php');
    include($parameters['path'].'/wp-admin/includes/upgrade.php');

    include('seeds/'.$environment.'/seed.php');

    echo "Database seeding complete\n";
  }

  function writeWhippetWpConfig($parameters) {
    $db = $parameters['db'];
    $s = "<?php # Generated by the tests\n";
    foreach ($db as $k => $v) {
      $kk = strtoupper($k);
      $s .= "define('DB_$kk', '$v');\n";
    }

    $s .= "define('WP_CONTENT_DIR', __DIR__.'/../../wp-content');\n";

    file_put_contents($parameters['path'].'/whippet-wp-config.php', $s);

    $s .= "define('WP_HOME', 'http://localhost:".$parameters['port']."' );\n";
    $s .= "define('WP_SITEURL', WP_HOME);\n";
    $s .= "\$table_prefix  = 'wp_';\n";
    $s .= "define ('WPLANG', '');\n";
    $s .= "if ( !defined('ABSPATH') ) define('ABSPATH', dirname(__FILE__) . '/');\n";
    $s .= "require_once(ABSPATH . 'wp-settings.php');\n";

    file_put_contents($parameters['path'].'/wp-config.php', $s);
  }
};
