<?php

class Db extends RubbishThorClone {
  use manifest_io;
  use whippet_helpers;

  public function commands() {
    $this->command('seed [ENV]', 'Seeds the database for the appropriate environment');
  }

  /*
   * Commands
   */

  public function seed($environment) {
    if (!is_string($environment)) {
      echo "Usage: whippet db seed testing\n";
      exit(1);
    }

    $this->whippet_init();

    $this->writeWhippetWpConfig([
      'DB_HOST' => '192.168.1.147',
      'DB_NAME' => 'behat_testing',
      'DB_USER' => 'root',
      'DB_PASSWORD' => '',
    ]);

    // Load WP
    define('WP_INSTALLING', true);
    define('NEW_MEMBERS_ONLY_PASSTHROUGH', true);

    include('web/wp/wp-load.php');
    include('web/wp/wp-content/plugins/advanced-custom-fields/acf.php');

    include('seeds/'.$environment.'/seed.php');

    echo "Database seeding complete\n";
  }

  function writeWhippetWpConfig($parameters) {
    $s = "<?php # Generated by whippet\n";
    foreach ($parameters as $k => $v) {
      $s .= "define('$k', '$v');\n";
    }

    file_put_contents('web/wp/whippet-wp-config.php', $s);

    // $s .= "define('WP_HOME', 'http://localhost:".$this->port."' );\n";
    // $s .= "define('WP_SITEURL', WP_HOME);\n";
    $s .= "\$table_prefix  = 'wp_';\n";
    $s .= "define ('WPLANG', '');\n";
    $s .= "if ( !defined('ABSPATH') ) define('ABSPATH', dirname(__FILE__) . '/');\n";
    $s .= "require_once(ABSPATH . 'wp-settings.php');\n";

    file_put_contents('web/wp/wp-config.php', $s);
  }
};
