<?php

class Db extends RubbishThorClone {
  use manifest_io;
  use whippet_helpers;

  public function commands() {
    $this->command('seed [ENV]', 'Seeds the database for the appropriate environment');
  }

  /*
   * Commands
   */

  public function seed($environment) {
    if (!is_string($environment)) {
      echo "Usage: whippet db seed testing\n";
      exit(1);
    }

    $this->whippet_init();

    $yaml = \Symfony\Component\Yaml\Yaml::parse('whippet.yml');
    $parameters = $yaml['whippet'][$environment];

    $this->writeWhippetWpConfig($parameters);

    // Load WP
    define('WP_INSTALLING', true);
    define('NEW_MEMBERS_ONLY_PASSTHROUGH', true);

    include('web/wp/wp-load.php');
    include('web/wp/wp-admin/includes/upgrade.php');

    global $wpdb;
    $tables = $wpdb->get_col('SHOW TABLES');
    foreach ($tables as $table) {
      $wpdb->query('drop table '.$table);
      echo "dropped $table\n";
    }

    include('seeds/'.$environment.'/seed.php');

    echo "Database seeding complete\n";
  }

  function writeWhippetWpConfig($db) {
    $s = "<?php # Generated by the tests\n";
    foreach ($db as $k => $v) {
      $kk = strtoupper($k);
      $s .= "define('DB_$kk', '$v');\n";
    }

    $s .= "define('WP_CONTENT_DIR', __DIR__.'/../../wp-content');\n";

    file_put_contents('web/wp/whippet-wp-config.php', $s);

    $s .= "define('WP_HOME', 'http://localhost:".$this->whippet->port."' );\n";
    $s .= "define('WP_SITEURL', WP_HOME);\n";
    $s .= "\$table_prefix  = 'wp_';\n";
    $s .= "define ('WPLANG', '');\n";
    $s .= "if ( !defined('ABSPATH') ) define('ABSPATH', dirname(__FILE__) . '/');\n";
    $s .= "require_once(ABSPATH . 'wp-settings.php');\n";

    file_put_contents('web/wp/wp-config.php', $s);
  }
};
