#!/bin/sh

# script/test: Run the test suite for the application. Optionally pass in a path
#              to an individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
	set -x
fi

echo "==> Updating..."
script/update

echo "==> Running ShellCheck..."
./.shellcheck.sh

echo "==> Running code formatter..."
cargo fmt

echo "==> Running code linter..."
cargo clippy

echo "==> Running the tests..."
cargo test
