name: Tests & Linting

on: push

jobs:
  run:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
      fail-fast: false
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v4.0.1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: git config (required for PluginsTest)
      run: git config --global user.email you@example.com && git config --global user.name you

    - name: Run lints and tests
      run: ./script/test
    
    - name: Run Psalm for this specific PHP version
      run: ./vendor/bin/psalm --php-version=${{ matrix.php-versions }}
